version: '3.8'

services:
  db_dev:
    image: postgis/postgis
    restart: always
    environment:
      POSTGRES_USER: dev_user_eduverify
      POSTGRES_PASSWORD: dev_eduverify2024
      POSTGRES_DB: dev_database_eduverify
    ports:
      - '5432:5432'
    volumes:
      - db_dev_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  db_dev_data:
